# Generated by Django 4.2.5 on 2023-12-12 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voucher",
            old_name="code",
            new_name="connection_code",
        ),
    ]
