# Generated by Django 4.2.5 on 2023-12-14 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0002_rename_code_voucher_connection_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="date",
            field=models.DateField(default=datetime.date(2023, 12, 14)),
        ),
    ]
