# Generated by Django 4.2.5 on 2023-12-20 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0003_alter_voucher_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="date",
            field=models.DateField(default=datetime.date(2023, 12, 20)),
        ),
    ]
