# Generated by Django 4.2.5 on 2024-02-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vouchers", "0004_alter_voucher_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
