# Generated by Django 4.2.5 on 2023-10-04 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 4, 17, 16, 4, 734565, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
