# Generated by Django 4.2.5 on 2023-10-04 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_alter_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 4, 17, 16, 40, 382468, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
