# Generated by Django 4.2.5 on 2023-10-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0007_alter_subscription_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="daily_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
