# Generated by Django 4.2.5 on 2023-10-27 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0009_alter_subscription_billing_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(default=datetime.date(2023, 10, 27)),
        ),
    ]
