# Generated by Django 4.2.5 on 2023-11-07 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0011_plan_navigation_speed_alter_subscription_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(default=datetime.date(2023, 11, 6)),
        ),
    ]
