# Generated by Django 4.2.5 on 2023-11-09 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0013_alter_subscription_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2023, 11, 9, 13, 58, 50, 585344, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
