# Generated by Django 4.2.5 on 2023-12-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0016_subscription_auto_renew"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="slug_name",
            field=models.SlugField(default="hola", max_length=40),
            preserve_default=False,
        ),
    ]
