# Generated by Django 4.2.5 on 2023-12-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0017_plan_slug_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="slug_name",
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
