# Generated by Django 4.2.5 on 2024-02-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0019_alter_plan_slug_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="slug_name",
            field=models.SlugField(help_text="Ruijie or Altai plan name", max_length=40, unique=True),
        ),
    ]
