# Generated by Django 4.2.5 on 2023-12-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_location_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.DecimalField(decimal_places=5, max_digits=8, verbose_name="latitude"),
        ),
        migrations.AlterField(
            model_name="location",
            name="long",
            field=models.DecimalField(decimal_places=5, max_digits=8, verbose_name="longitude"),
        ),
    ]
