# Generated by Django 4.2.5 on 2023-09-26 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="mac",
            field=models.CharField(
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid MAC address.", regex="^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"
                    )
                ],
            ),
        ),
    ]
