# Generated by Django 4.2.5 on 2023-10-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0002_alter_device_mac"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="brand",
            new_name="device_id",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="model",
            new_name="token",
        ),
        migrations.RemoveField(
            model_name="device",
            name="mac",
        ),
        migrations.AddField(
            model_name="device",
            name="os",
            field=models.CharField(choices=[("android", "android"), ("ios", "ios")], default="android"),
        ),
    ]
