# Generated by Django 4.2.5 on 2023-11-07 01:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0004_alter_device_device_id_alter_device_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="device_id",
        ),
    ]
