# Generated by Django 4.2.5 on 2023-09-23 01:51

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_location"),
        ("users", "0002_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="municipality",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="state",
                chained_model_field="state",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.municipality",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="locations.state"),
        ),
    ]
