# Generated by Django 4.2.5 on 2023-10-04 01:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_balance"),
        ("users", "0005_user_id_number"),
    ]

    operations = []
