# Generated by Django 4.2.5 on 2024-02-02 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_users_user_usernam_65d164_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id_number",
            field=models.CharField(
                db_index=True,
                max_length=9,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(message="Invalid CI.", regex="^[V|E|J|P|G][0-9]{8}$")
                ],
            ),
        ),
    ]
