# Generated by Django 4.2.5 on 2024-02-02 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_id_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id_number",
            field=models.CharField(
                db_index=True,
                help_text="DNI number",
                max_length=9,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(message="Invalid CI.", regex="^[V|E|J|P|G][0-9]{8}$")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                db_index=True,
                help_text="Example: +584121234567",
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: +999999999. Up to 15 digits allowed.",
                        regex="\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
