# Generated by Django 4.2.5 on 2023-10-02 12:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("prev_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("post_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("code", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "operation_type",
                    models.CharField(choices=[("R", "Recharge"), ("P", "Payment")], default="R", max_length=1),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Recharge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)]
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(choices=[("PM", "Pago móvil"), ("DC", "Debit card")], default="PM", max_length=2),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="recharge", to="operations.operation"
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PagoMovil",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("operation_time_stamp", models.DateTimeField()),
                ("reference_number", models.CharField(max_length=10, unique=True)),
                ("origin_phone_number", models.CharField()),
                ("recipient_phone_number", models.CharField()),
                ("status", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=255)),
                ("ref_pk", models.CharField(max_length=100, unique=True)),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("0102", "Banco de Venezuela, S.A.C.A."),
                            ("0104", "Venezolano de Crédito"),
                            ("0105", "Mercantil"),
                            ("0108", "Provincial"),
                            ("0114", "Bancaribe"),
                            ("0115", "Exterior"),
                            ("0116", "Occidental de Descuento"),
                            ("0128", "Banco Caroní"),
                            ("0134", "Banesco"),
                            ("0138", "Banco Plaza"),
                            ("0151", "BFC Banco Fondo Común"),
                            ("0156", "100% Banco"),
                            ("0157", "Del Sur"),
                            ("0163", "Banco del Tesoro"),
                            ("0166", "Banco Agrícola de Venezuela"),
                            ("0168", "Bancrecer"),
                            ("0169", "Mi Banco"),
                            ("0171", "Banco Activo"),
                            ("0172", "Bancamiga"),
                            ("0174", "Banplus"),
                            ("0175", "Bicentenario del Pueblo"),
                            ("0177", "Banfanb"),
                            ("0191", "BNC Nacional de Crédito"),
                        ],
                        default="0172",
                        max_length=4,
                    ),
                ),
                ("request_body", models.JSONField()),
                (
                    "recharge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pago_movil",
                        to="operations.recharge",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
