# Generated by Django 4.2.5 on 2024-02-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0004_transfer_concept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagomovil",
            name="reference_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
