# Generated by Django 4.2.5 on 2024-02-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0005_alter_pagomovil_reference_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagomovil",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
